### ISSUE TITLE
handle problem

### ISSUE THREAD

**Issue by aios** [xembly/validate-workflow-status#1]
```Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ValidateWorkflow.Program.<>c__DisplayClass1_0.<Main>b__0(IServiceProvider _) in C:\Users\aroem\Sources\xembly-validate-workflow-status\ValidateWorkflow\Program.cs:line 32
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
....
at ValidateWorkflow.Program.<>c__DisplayClass1_0.<Main>b__0(IServiceProvider _) in C:\Users\aroem\Sources\xembly-validate-workflow-status\ValidateWorkflow\Program.cs:line 32
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at ValidateWorkflow.Program.<>c.<<-cctor>b__2_0>d.MoveNext() in C:\Users\aroem\Sources\xembly-validate-workflow-status\ValidateWorkflow\Program.cs:line 13
--- End of stack trace from previous location where exception was thrown ---
   at ValidateWorkflow.Program.Main(String[] args) in C:\Users\aroem\Sources\xembly-validate-workflow-status\ValidateWorkflow\Program.cs:line 45
   at ValidateWorkflow.Program.<Main>(String[] args)
Aborted (core dumped)```

Something like that after install to yml workflow

**Comment by aroemen** [comment]
Sorry @aios, I didn't see the notification for this issue come through. Can you provide more information on your workflow configuration for this action? It appears the action isn't getting all the required params.
